//Vamos a exportar el arreglo de datos
export const productosSelecto = [
    {
        id: 1,
        categoria: "ceras", 
        imagen: "/4_pagServicios/assetsServicios/productos/RedOne-black.png", 
        nombre: "Cera Red One Black" ,
        subtitulo: "Aqua hair wax full force maximum control",
        precio:"48.000",
        stock: 10,
        descripcion: "Cera fuerte creada con la combinación híbrida única entre gel y cera para el cabello, que proporciona un look impecable y de larga duración capaz de aguantar todo el día. Es muy fácil de enjuagar y ofrece un suave control y brillo, con olor a perfume masculino.",
        cantidad: 1,
        etiqueta: "nuevo"
    },
    {
        id: 2,
        categoria: "ceras", 
        imagen: "/4_pagServicios/assetsServicios/productos/RedOne-blue.jpg", 
        nombre: "Cera Red One Blue" ,
        subtitulo: "Aqua hair wax full force maximum control",
        precio:"48.000",
        stock: 10,
        descripcion: "Cera fuerte creada con la combinación híbrida única entre gel y cera para el cabello, que proporciona un look impecable y de larga duración capaz de aguantar todo el día. Es muy fácil de enjuagar y ofrece un suave control y brillo, con olor a cliche.",
        cantidad: 1,
        etiqueta: "nuevo"
    },
    {
        id: 3,
        categoria: "ceras", 
        imagen: "/4_pagServicios/assetsServicios/productos/RedOne-green.jpg", 
        nombre: "Cera Red One Green" ,
        subtitulo: "Matte hair wax full force maximum control",
        precio:"48.000",
        stock: 10,
        descripcion: "Cera con un acabado mate. Tiene una fórmula enriquecida con vitaminas. Además, el cabello se mantiene en forma durante todo el día. La cera es ideal para todo tipo de cabello con un delicioso aroma dulce a manzana verde.",
        cantidad: 1,
        etiqueta: "nuevo"
    },
    {
        id: 4,
        categoria: "ceras", 
        imagen: "/4_pagServicios/assetsServicios/productos/RedOne-orange.jpg", 
        nombre: "Cera Red One Orange" ,
        subtitulo: "Aqua hair wax full force",
        precio:"48.000",
        stock: 10,
        descripcion: "Cera fuerte creada con la combinación híbrida única entre gel y cera para el cabello, que proporciona un look impecable y de larga duración capaz de aguantar todo el día. Es muy fácil de enjuagar y ofrece un suave control y brillo, con olor a frutas tropicales.",
        cantidad: 1,
        etiqueta: "nuevo"
    },
    {
        id: 5,
        categoria: "ceras", 
        imagen: "/4_pagServicios/assetsServicios/productos/RedOne-Red.webp", 
        nombre: "Cera Red One Red" ,
        subtitulo: "Aqua hair wax full force maximum control",
        precio:"48.000",
        stock: 10,
        descripcion: "Cera con un acabado mate. Tiene una fórmula enriquecida con vitaminas. Además, el cabello se mantiene en forma durante todo el día. La cera es ideal para todo tipo de cabello con un delicioso aroma a frutas tropicales.",
        cantidad: 1,
        etiqueta: "nuevo"
    },
    {
        id: 6,
        categoria: "ceras", 
        imagen: "/4_pagServicios/assetsServicios/productos/NishMan-blue.jpg", 
        nombre: "Cera Nish Man Blue" ,
        subtitulo: "StylingCream Natural look",
        precio:"30.000",
        stock: 10,
        descripcion: "Funciona muy bien con todos los tipos de cabello para crear cualquier aspecto, controla al cabello rebelde, rizado, grueso o áspero; mejorando su definición y estructura, dando forma con facilidad.",
        cantidad: 1,
        etiqueta: "nuevo"
    },
    {
        id: 7,
        categoria: "ceras", 
        imagen: "/4_pagServicios/assetsServicios/productos/NishMan-gold.jpg", 
        nombre: "Cera Nish Man Gold",
        subtitulo: "Hair styling wax",
        precio:"30.000",
        stock: 10,
        descripcion: "Funciona muy bien con todos los tipos de cabello para crear cualquier aspecto, controla al cabello rebelde, rizado, grueso o áspero; mejorando su definición y estructura, dando forma con facilidad.",
        cantidad: 1,
        etiqueta: "nuevo"
    },
    {
        id: 8,
        categoria: "ceras", 
        imagen: "/4_pagServicios/assetsServicios/productos/NishMan-green.jpg", 
        nombre: "Cera Nish Man Green",
        subtitulo: "Hair styling wax Keratin",
        precio:"30.000",
        stock: 10,
        descripcion: "Funciona muy bien con todos los tipos de cabello para crear cualquier aspecto, controla al cabello rebelde, rizado, grueso o áspero; mejorando su definición y estructura, dando forma con facilidad.",
        cantidad: 1,
        etiqueta: "nuevo"
    },
    {
        id: 9,
        categoria: "ceras", 
        imagen: "/4_pagServicios/assetsServicios/productos/NishMan-mate.jpg", 
        nombre: "Cera Nish Man Green",
        subtitulo: "Hair styling pliable matte",
        precio:"30.000",
        stock: 10,
        descripcion: "Funciona muy bien con todos los tipos de cabello para crear cualquier aspecto, controla al cabello rebelde, rizado, grueso o áspero; mejorando su definición y estructura, dando forma con facilidad.",
        cantidad: 1,
        etiqueta: "nuevo"
    },
    {
        id: 10,
        categoria: "ceras", 
        imagen: "/4_pagServicios/assetsServicios/productos/NishMan-orange.jpg", 
        nombre: "Cera Nish Man Orange",
        subtitulo: "Hair styling wax Sport",
        precio:"30.000",
        stock: 10,
        descripcion: "Funciona muy bien con todos los tipos de cabello para crear cualquier aspecto, controla al cabello rebelde, rizado, grueso o áspero; mejorando su definición y estructura, dando forma con facilidad.",
        cantidad: 1,
        etiqueta: "nuevo"
    },
    {
        id: 11,
        categoria: "ceras", 
        imagen: "/4_pagServicios/assetsServicios/productos/NishMan-red.jpg", 
        nombre: "Cera Nish Man Red",
        subtitulo: "Hair styling wax Sport",
        precio:"30.000",
        stock: 10,
        descripcion: "Funciona muy bien con todos los tipos de cabello para crear cualquier aspecto, controla al cabello rebelde, rizado, grueso o áspero; mejorando su definición y estructura, dando forma con facilidad.",
        cantidad: 1,
        etiqueta: "nuevo"
    },
    {
        id: 12,
        categoria: "tónicos", 
        imagen: "/4_pagServicios/assetsServicios/productos/Minoxidil.jpeg", 
        nombre: "Minoxidil",
        subtitulo: "Tónico para crecimiento del cabello",
        precio:"48.000",
        stock: 10,
        descripcion: "Especial para el crecimiento de la barba, permite tener una mejor irrigación sanguínea, estimula y nutre el folículo capilar, aumenta y empareja la barba, además de hidratar profundamente.",
        cantidad: 1,
        etiqueta: "nuevo"
    },
    {
        id: 13,
        categoria: "tónicos", 
        imagen: "/4_pagServicios/assetsServicios/productos/Minoxigrowjpg.jpg", 
        nombre: "Minoxigrow",
        subtitulo: "Tónico para crecimiento del cabello",
        precio:"48.000",
        stock: 10,
        descripcion: "tónico  de última generación con compuestos de comprobada eficiencia para el crecimiento del cabello, barba y bigote. Combina tres elementos de eficiencia comprobada para el tratamiento  de la alopecia Calvicie) : minoxidil, saw palmeto (Bloqueador de DHT) y Biotina",
        cantidad: 1,
        etiqueta: "nuevo"
    },
    {
        id: 14,
        categoria: "máquinas", 
        imagen: "/4_pagServicios/assetsServicios/productos/shaver_Kemel.jpg", 
        nombre: "Shaver Kamei",
        subtitulo: "Maquinilla de afeitar eléctrica",
        precio:"140.000",
        stock: 10,
        descripcion: "Posee laminas hipoalergenicas de titanio y oro para afeitadas sin irritación. Sus hojas escalonadas permiten un afeitado mas al ras. Con una sola carga ofrece hasta 90 min de autonomía de corte.",
        cantidad: 1,
        etiqueta: "nuevo"
    },
    {
        id: 15,
        categoria: "máquinas", 
        imagen: "/4_pagServicios/assetsServicios/productos/shaver_Vgr.jpg", 
        nombre: "Shaver VGR",
        subtitulo: "Maquinilla de afeitar eléctrica",
        precio:"140.000",
        stock: 10,
        descripcion: "cuerpo entero impermeable, afeitado seco y húmedo, limpieza rápida. Voltaje Universal, viaja por todo el mundo sin temor a agotarse la electricidad. Carga USB y conexión de doble propósito, carga rápida durante 2 horas se puede utilizar durante 90 minutos.",
        cantidad: 1,
        etiqueta: "nuevo"
    },
    {
        id: 16,
        categoria: "lacas", 
        imagen: "/4_pagServicios/assetsServicios/productos/laca_RedOne.jpg", 
        nombre: "Laca Red One ultra hold",
        subtitulo: "Hair styling spray",
        precio:"50.000",
        stock: 10,
        descripcion: "Laca para el cabello de fijación completa y fuerte para formas y texturas creativas. Da forma duradera y de aspecto natural a tu cabello y se peina fácilmente debido a su estructura de grano fino.",
        cantidad: 1,
        etiqueta: "nuevo"
    },
    {
        id: 17,
        categoria: "cerveza", 
        imagen: "/4_pagServicios/assetsServicios/productos/Heineken .png", 
        nombre: "Heineken",
        subtitulo: "",
        precio:"4.000",
        stock: 10,
        descripcion: "En medio de la atmósfera de refinamiento de nuestra barbería, Heineken se convierte en el complemento ideal, elevando cada experiencia a un nivel superior de distinción.",
        cantidad: 1,
        etiqueta: "nuevo"
    }
];

